"""empty message

Revision ID: 3c08e474d28b
Revises: 4fa14291615f
Create Date: 2021-02-28 22:02:10.262542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c08e474d28b'
down_revision = '4fa14291615f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('outofdate', sa.Boolean(), nullable=True))
    op.alter_column('app', 'Kdate',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('app', 'Kvalue',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('face', 'Fsrc',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('face', 'Fsrc',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('app', 'Kvalue',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('app', 'Kdate',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('app', 'outofdate')
    # ### end Alembic commands ###
