"""empty message

Revision ID: 4fa14291615f
Revises: c7c8ced99a84
Create Date: 2021-02-25 12:25:58.071915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fa14291615f'
down_revision = 'c7c8ced99a84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face', sa.Column('Fencoding', sa.String(length=1024), nullable=False))
    op.alter_column('face', 'Fsrc',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('face', 'Fsrc',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('face', 'Fencoding')
    # ### end Alembic commands ###
