"""empty message

Revision ID: d667a12885a7
Revises: 
Create Date: 2021-02-09 00:27:09.326022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd667a12885a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('Aid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Aname', sa.String(length=30), nullable=False),
    sa.Column('Apwd', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('Aid')
    )
    op.create_table('developer',
    sa.Column('Did', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Dname', sa.String(length=20), nullable=False),
    sa.Column('Dpwd', sa.String(length=30), nullable=True),
    sa.Column('Dtel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Did')
    )
    op.create_table('record',
    sa.Column('Rid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Rtime', sa.Time(), nullable=False),
    sa.Column('Rtype', sa.String(length=10), nullable=False),
    sa.Column('Ritemid', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('Rid')
    )
    op.create_table('app',
    sa.Column('Apid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Apname', sa.String(length=30), nullable=True),
    sa.Column('Did', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Did'], ['developer.Did'], ),
    sa.PrimaryKeyConstraint('Apid')
    )
    op.create_table('appkey',
    sa.Column('Kid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Did', sa.Integer(), nullable=False),
    sa.Column('Kvalue', sa.String(length=50), nullable=False),
    sa.Column('Kdate', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['Did'], ['developer.Did'], ),
    sa.PrimaryKeyConstraint('Kid')
    )
    op.create_table('face',
    sa.Column('Fid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Fsrc', sa.String(length=100), nullable=False),
    sa.Column('Fname', sa.String(length=30), nullable=True),
    sa.Column('Apid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Apid'], ['app.Apid'], ),
    sa.PrimaryKeyConstraint('Fid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face')
    op.drop_table('appkey')
    op.drop_table('app')
    op.drop_table('record')
    op.drop_table('developer')
    op.drop_table('admin')
    # ### end Alembic commands ###
