"""empty message

Revision ID: dc54049e39c9
Revises: af44255253a9
Create Date: 2021-03-07 10:50:34.194566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc54049e39c9'
down_revision = 'af44255253a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developer', sa.Column('Dmale', sa.Boolean(), nullable=True))
    op.alter_column('record', 'Rtime',
               existing_type=mysql.DATETIME,
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('developer', 'Dmale')
    op.alter_column('record', 'Rtime',
                    existing_type=mysql.TIME,
                    nullable=False)
    # ### end Alembic commands ###
